{
 "title": "Reverse Proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_upstream_active_connections",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "In-flight Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_inflight_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(proxy_requests_total{status=~\"4..|5..\"}[1m]) / (rate(proxy_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(proxy_requests_total[1m])", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(proxy_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(proxy_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(proxy_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request Volume Per Upstream",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(proxy_upstream_requests_total[1m])",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(proxy_upstream_response_seconds_bucket[5m]))",
     "legendFormat": "{{upstream}}"
    }
   ]
  }
 ]
}